from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .pedido import Pedido as PedidoResource
from .pedido import Pedidos as PedidosResource
from .comida import Comida as ComidaResource 
from .comida import Comidas as ComidasResource
from .resena import Resena as ResenaResource
from .resena import Resenas as ResenasResource
from .notificacion import Notificacion as NotificacionResource
from .notificacion import Notificaciones as NotificacionesResource
from .anadir_carrito import Anadir_carrito as Añadir_carritoResource